sudo: false

language: node_js
node_js:
  - "12"

services:
  - docker

notifications:
  email: false

branches:
  only:
    - master

addons:
  apt:
    packages:
      - chromium-browser

cache:
  directories:
    - ./web/onos-gui/node_modules

before_script:
  - pushd .. && git clone https://github.com/onosproject/build-tools.git && popd

before_install:
  - 'if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" ]] ; then
       openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv -in .ssh/id_rsa.enc -out ~/.ssh/id_rsa -d &&
       chmod 600 ~/.ssh/id_rsa;
     fi'

install:
  - npm install -g @angular/cli
  - cd web/onos-gui && npm install && cd ../..

jobs:
  include:
    - stage: tests
      if: type == pull_request || fork == false
      script:
        - make test
    - stage: docs build
      if: type != pull_request && fork == false
      script:
        - sh build/bin/trigger-docs-travis $TRAVIS_ACCESS_TOKEN
    - stage: release
      if: type != pull_request && fork == false
      script:
        - bash ./build/bin/push-images
        - bash ../build-tools/release-merge-commit
